### ISSUE TITLE
Подключение Twitter API

### ISSUE THREAD

**Issue by naffiq** [aziza-kamet/twitter-map#1]
Добрый день, стучусь к вам из Ракетной :)

Для решения тестового нужно подключить Twitter API и отображать на карте реальные данные пользователей, давайте вы подключите их и закроете этот issue. После этого я еще раз проверю ваше тестовое задание.

Удачи!

**Comment by aziza-kamet** [comment]
@naffiq Простите, неправильно поняла задание :) Обязательно все исправлю

**Comment by naffiq** [comment]
И ещё, привязывать пользователей к твитам необязательно, достаточно просто получать твиты из API и сохранять их в БД. Отдельным методом нужно выдавать их из БД.

**Comment by aziza-kamet** [comment]
@naffiq А твиты нужно получать и выдавать в realtime?

**Comment by naffiq** [comment]
@aziza-kamet достаточно вывести кнопку в интерфейс, которая будет производить ручную синхронизацию

**Comment by aziza-kamet** [comment]
Подключилась к TwitterAPI используя пакет [https://github.com/thujohn/twitter](https://github.com/thujohn/twitter).
В начале хотела использовать запрос [statuses/sample](https://developer.twitter.com/en/docs/tweets/sample-realtime/overview/GET_statuse_sample), который возвращает рандомные твиты, но он у меня почему-то возвращал только `null`. Потом хотела доставать из [таймлайна](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline.html), но там были проблемы с определением указана ли локация в твите, или нет, так как в самом запросе это не учитывается. Так и не смогла найти запрос, который бы доставал только твиты с локациями, и в итого решила просто отправлять поисковой запрос. Надеюсь мое решение хоть немного подойдет, так как главные критерии:

>  подключить Twitter API и отображать на карте реальные данные пользователей
> ... достаточно просто получать твиты из API и сохранять их в БД. Отдельным методом нужно выдавать их из БД

были выполнены :)
